Repository flutter-es/website, pull requests merged in 2018-10, with the labels that each got.

#334 Correcciones getstarted/learn-more
  es_ES/get-started/learn-more.md
Labels: Correcciones

#340 traducción de root_upgrading commit1
  es_ES/upgrading.md
  es_ES/using-packages.md
  upgrading.md
  using-packages.md
Labels: Traducción

#341 traducción de root_technical_overview commit1
  es_ES/technical-overview.md
Labels: Traducción

#342 traducción de root_support commit1
  es_ES/support.md
Labels: Traducción

#343 traducción de root_bug_reports commit1
  es_ES/bug_reports.md
Labels: Traducción

#346 Traducción fastlane.md
  es_ES/fastlane.md
Labels: Traducción

#347 Design principles
  es_ES/design-principles.md
Labels: Traducción

#337 Correción animations/staggered-animations/index.md
  es_ES/animations/staggered-animations/index.md
Labels: Correcciones

#349 ios-release
  es_ES/ios-release-build.md
Labels: Traducción

#350 Banner Flutter Live 2018
  _config.yml
  _includes/banner.html
  _layouts/default.html
  _sass/_customstyles.scss
  _sass/_homepage.scss
  es_ES/_includes/banner.html
Labels: Actualizaciones fork
