Repository flutter-es/website, pull requests merged in 2018-08, with the labels that each got.

#17 corrección errata
  es_ES/README.md
Labels: Ortografía

#12 layout.md
  es_ES/layout.md
Labels: Traducción

#19 Traducción del archivo accessiblity.md
  es_ES/accessiblity.md
Labels: Traducción

#29 correcciones varias
  .gitignore
  es_ES/index.md
Labels: Correciones

#25 traducción de docs.md
  es_ES/_data/docs_cards.yml
  es_ES/docs.md
Labels: Traducción

#35 Broken link engine build sh
  design-principles.md
Labels: bug

#33 gestures.md
  es_ES/gestures.md
  es_ES/layout.md
Labels: Traducción

#160 Get started lean more corrección
  es_ES/get-started/learn-more.md
Labels: Correcciones

#163 Layouts
  _layouts/default.html
  _layouts/page.html
  _layouts/tutorial.html
Labels: Correcciones

#166 Traducción de inspector.md
  es_ES/inspector.md
Labels: Traducción

#172 Correcciones sidebar
  es_ES/_includes/sidebar.html
Labels: Correcciones

#171 widget-intro.md Correción enlace
  es_ES/widgets-intro.md
Labels: Correcciones

#173 traducción de mocking
  .gitignore
  _config.yml
  es_ES/cookbook/testing/mocking.md
Labels: Traducción

#176 indice de cookbook
  es_ES/cookbook/index.md
Labels: Traducción

#175 Correccione index.md túteo
  es_ES/index.md
Labels: Correcciones

#170 traducción de unit_test
  es_ES/cookbook/testing/unit-test.md
Labels: Traducción

#159 Widget index
  es_ES/_data/catalog/widgets.json
  es_ES/widgets/widgetindex.md
Labels: Traducción

#178 Corrección mantenimiento
  es_ES/cookbook/index.md
Labels: Correcciones

#186 traducción de fonts commit1
  es_ES/cookbook/design/fonts.md
Labels: Traducción

#187 traducción de package-fonts commit1
  es_ES/cookbook/design/package-fonts.md
Labels: Traducción

#218 cambios en estructura de capertas de flutter/website
  _layouts/page.html
  animations/hero-animations/index.md
  animations/staggered-animations/index.md
  cookbook/images/cached-images.md
  cookbook/images/fading-in-images.md
  cookbook/images/network-image.md
  cookbook/navigation/hero-animations.md
  design-principles.md
  es_ES/cookbook/images/cached-images.md
  es_ES/cookbook/images/fading-in-images.md
  es_ES/cookbook/images/network-image.md
  tutorials/animation/index.md
  tutorials/interactive/index.md
  tutorials/international/index.md
  tutorials/layout/index.md
Labels: Actualizaciones fork

#222 Traduccion cookbook/design/themes.md
  es_ES/cookbook/design/themes.md
Labels: Traducción

#220 indices de widgets
  es_ES/_data/catalog/index.json
  es_ES/_data/catalog/widgets.json
  es_ES/widgets/accessibility.md
  es_ES/widgets/animation.md
  es_ES/widgets/assets.md
  es_ES/widgets/async.md
  es_ES/widgets/basics.md
  es_ES/widgets/cupertino.md
  es_ES/widgets/input.md
  es_ES/widgets/interaction.md
  es_ES/widgets/layout.md
  es_ES/widgets/materialdesign.md
  es_ES/widgets/painting.md
  es_ES/widgets/scrolling.md
  es_ES/widgets/styling.md
  es_ES/widgets/text.md
  widgets.md
Labels: Traducción

#219 web-analogs.md
  es_ES/web-analogs.md
Labels: Traducción

#188 traducción tutorial de layouts
  es_ES/tutorials/layout/index.md
Labels: Traducción

#221 Traducción de Cookbook/networking/
  es_ES/cookbook/networking/authenticated-requests.md
  es_ES/cookbook/networking/background-parsing.md
  es_ES/cookbook/networking/fetch-data.md
  es_ES/cookbook/networking/web-sockets.md
Labels: Traducción

#227 traducción de hero-animations commit1
  es_ES/cookbook/navigation/hero-animations.md
Labels: Traducción

#226 traducción de navigation-basics commit1
  es_ES/cookbook/navigation/navigation-basics.md
Labels: Traducción

#225 traducción de named-routes commit1
  es_ES/cookbook/navigation/named-routes.md
Labels: Traducción

#233 revisiones getstarted reacondicionado
  es_ES/_includes/setup/android-setup.md
  es_ES/_includes/setup/get-sdk-win.md
  es_ES/_includes/setup/get-sdk.md
  es_ES/_includes/setup/ios-setup.md
  es_ES/_includes/setup/path-mac-linux.md
  es_ES/_includes/setup/system-mac.md
  es_ES/_includes/setup/system-win.md
  es_ES/get-started/editor.md
  es_ES/get-started/install.md
  es_ES/get-started/setup_macos.md
  es_ES/get-started/test-drive.md
Labels: Correcciones

#239 faltaba un espacio en el enlace al catálogo
  widgets.md
Labels: Correcciones

#240 correciones fastlane.md desde upstream
  fastlane.md
Labels: Actualizaciones fork

#242 cambios upstream ui-performance/index.md
  ui-performance/index.md
Labels: Actualizaciones fork

#241 upstream correccion platform-channels
  platform-channels.md
Labels: Actualizaciones fork

#224 traducción cookbook/navigation/passing-data.md
  es_ES/cookbook/navigation/passing-data.md
Labels: Traducción

#265 traducción catalog/samples/ExpaionTile_index
  es_ES/catalog/samples/ExpansionTile_index.md
Labels: Traducción

#264 traducción catalog/samples/expansion_tile_sample
  es_ES/catalog/samples/expansion_tile_sample.md
Labels: Traducción

#263 traducción catalog/samples/DefaultTabController_index
  es_ES/catalog/samples/DefaultTabController_index.md
Labels: Traducción

#262 traducción catalog/samples/basic_app_bar
  es_ES/catalog/samples/basic_app_bar.md
Labels: Traducción

#261 traducción catalog/samples/AppBar_index
  es_ES/catalog/samples/AppBar_index.md
Labels: Traducción

#259 traducción catalog/samples/AnimatedListState_index
  es_ES/catalog/samples/AnimatedListState_index.md
Labels: Traducción

#258 traducción catalog/samples/AnimatedList_index
  es_ES/catalog/samples/AnimatedList_index.md
Labels: Traducción

#257 traducción catalog/samples/animated_list
  es_ES/catalog/samples/animated_list.md
Labels: Traducción

#266 developing packages
  es_ES/developing-packages.md
Labels: Traducción

#267 traducción de IconButton_index commit1
  es_ES/catalog/samples/IconButton_index.md
Labels: Traducción

#276 traducción catalog/samples/TabController_index
  es_ES/catalog/samples/TabController_index.md
Labels: Traducción

#235 traducción cookbook/persistence/key-value.md
  es_ES/cookbook/persistence/key-value.md
Labels: Traducción

#290 traduccion flutter-for-ios aprobada
  es_ES/flutter-for-ios.md
Labels: Traducción

#292 traducción aprobada de faq
  es_ES/faq.md
Labels: Traducción

#293 integration-test-scrolling correción aprobada, y revision daniel hecha
  es_ES/cookbook/testing/integration-test-scrolling.md
Labels: Traducción

#294 cookbook/testing/integration-test-profiling revisado y corregido
  es_ES/cookbook/testing/integration-test-profiling.md
Labels: Traducción

#295 Integration test intro corregido
  es_ES/cookbook/testing/integration-test-introduction.md
Labels: Traducción

#297 catalog/samples/Listviewindex aprobado
  es_ES/catalog/samples/ListView_index.md
Labels: Traducción

#298 catalog/samples/popmenu traduccion aprobada
  es_ES/catalog/samples/PopupMenuButton_index.md
Labels: Traducción

#299 traduccion aprobada codelab index
  es_ES/codelabs/index.md
Labels: Traducción
