Repository flutter-es/website, pull requests merged in 2018-09, with the labels that each got.

#310 traducción de showcase_index commit1
  es_ES/_data/showcases.yml
  es_ES/showcase/index.md
Labels: Traducción

#303 traducción tutorials/interactive/index.md
  es_ES/tutorials/interactive/index.md
Labels: Traducción

#305 traducción de react_native_idx commit1
  es_ES/flutter-for-react-native/index.md
Labels: Traducción

#300 Traducción de json.md
  es_ES/json.md
Labels: Traducción

#306 traducción tutorials/animation/index.md
  es_ES/tutorials/animation/index.md
Labels: Traducción

#309 traducción de ui_performance_index commit1
  es_ES/ui-performance/index.md
Labels: Traducción

#316 traduccion hot-reload.md
  es_ES/hot-reload.md
Labels: Traducción

#312 traducción search.md
  es_ES/search.md
Labels: Traducción

#313 traducción 404.md
  es_ES/404.md
Labels: Traducción

#314 traducción sdk-archive
  es_ES/sdk-archive.md
Labels: Traducción

#311 traduccion tutorials/intertanional/index.md
  es_ES/tutorials/international/index.md
  tutorials/international/index.md
Labels: Traducción

#322 traducción de flutter_for_android commit1
  es_ES/flutter-for-android.md
Labels: Traducción

#321 correción to por tú
  es_ES/json.md
Labels: Correcciones

#323 Using ide
  es_ES/using-ide.md
Labels: Traducción

#326 Close #45 Flutter Xamarin Forms
  es_ES/flutter-for-xamarin-forms.md
Labels: Traducción

#324 Animations
  es_ES/animations/hero-animations/index.md
  es_ES/animations/index.md
  es_ES/animations/overview.md
  es_ES/animations/staggered-animations/index.md
Labels: Traducción

#325 bootstrap-into-dart.md
  es_ES/bootstrap-into-dart.md
Labels: Traducción

#329 traducción de widgets_intro_rev commit1
  es_ES/widgets-intro.md
Labels: Correcciones

#332 Using ide vscode
  es_ES/using-ide-vscode.md
Labels: Traducción

#335 uptstream shocases
  es_ES/_data/showcases.yml
Labels: Actualizaciones fork

#345 Imágenes de nuevos widgets cupertino
  images/widget-catalog/cupertino-action-sheet.png
  images/widget-catalog/cupertino-segmented-control.png
  images/widget-catalog/cupertino-timer-picker.png
Labels: Actualizaciones fork
